# UPDATE THE PROXY ROUTE WITH THE ROUTE FROM YOUR TEST ENVIRONMENT
example:
  proxy:
    logout-url: http://localhost:8085/
proxy:
  permitAll:
    matches: /login,/*.js,/favicon.ico,*.map,/*.css,/robots.txt

zuul:
  add-proxy-headers: true
  sensitiveHeaders: Cookie,Set-Cookie
  ignoredPatterns: /**/health/**,/**/mappings/**
  ignored-services: "*"
  routes:
    angular-example:
      path: /angular-example/**
      url: http://localhost:4200/angular-example/
    auth-service:
      path: /auth-example/**
      url: http://localhost:4202/auth-example
      sensitiveHeaders: Authorization
      stripPrefix: false

security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8084/oauth/token
      userAuthorizationUri: http://localhost:8084/oauth/authorize
      clientId: zuul-proxy-example
      clientSecret: password
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzxi/2o2/xbs9UkLhL5Cw
          sU9MjUh7RQyHWuXl1bbFSVg/12Qfw5uGtqk2uSyiA8ND+/Ig3C98sbM4e5lQs6P9
          eeTPv05lYalaX9qZ81Y1y55jIa+tYg4Vylus1F52rDNMsX+ZCliK9KzL09N8qbh1
          D2obNQZF6bp5r25B7zoWgrM5wORP02MBWkjFbJ9+pacarikcyUll03C6vGj48X59
          wuqZjNBOIL+uM/adqjs3jwEpR3xAJUlclWaV8ogp4d56myL4ElgTPW3nKejFaV7c
          dy2/66+kYg1un2mTTwx6KJKL+T2DtpGW4imunC6mT/RxbJa4Ys2w/P3pyBViNijo
          IwIDAQAB
          -----END PUBLIC KEY-----

management:
  cloudfoundry:
    skip-ssl-validation: true

server:
  port: 8085

spring:
  aop:
    proxy-target-class: true

logging:
  level:
    ROOT: WARN
    org.springframework.security: DEBUG
