# UPDATE THE PROXY ROUTE WITH THE ROUTE FROM YOUR TEST ENVIRONMENT
example:
  proxy:
    logout-url: http://zuul-proxy-example.test.medzero.cfapps.io/angular-example
zuul:
  add-proxy-headers: true
  host:
    socket-timeout-millis: 3600
    connect-timeout-millis: 3600
  ignoredPatterns: /**/health/**,/**/mappings/**
  ignored-services: "*"
  # UPDATE THESE ROUTES WITH ROUTES FROM YOUR TEST ENVIRONMENT
  routes:
    auth-service:
      path: /auth-example/**
      url: http://auth-example.test.medzero.cfapps.io/
      sensitiveHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Credentials,Vary
    angular-example:
      path: /angular-example/**
      url: http://angular-example.test.medzero.cfapps.io/

security:
  oauth2:
    client:
      accessTokenUri: http://auth-example.test.medzero.cfapps.io/oauth/token
      userAuthorizationUri: http://auth-example.test.medzero.cfapps.io/oauth/authorize
      clientId: zuul-proxy-example
      clientSecret: password
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzxi/2o2/xbs9UkLhL5Cw
          sU9MjUh7RQyHWuXl1bbFSVg/12Qfw5uGtqk2uSyiA8ND+/Ig3C98sbM4e5lQs6P9
          eeTPv05lYalaX9qZ81Y1y55jIa+tYg4Vylus1F52rDNMsX+ZCliK9KzL09N8qbh1
          D2obNQZF6bp5r25B7zoWgrM5wORP02MBWkjFbJ9+pacarikcyUll03C6vGj48X59
          wuqZjNBOIL+uM/adqjs3jwEpR3xAJUlclWaV8ogp4d56myL4ElgTPW3nKejFaV7c
          dy2/66+kYg1un2mTTwx6KJKL+T2DtpGW4imunC6mT/RxbJa4Ys2w/P3pyBViNijo
          IwIDAQAB
          -----END PUBLIC KEY-----

management:
  cloudfoundry:
    skip-ssl-validation: true

server:
  servlet:
    session:
      cookie:
        name: UISESSION
      timeout: 60m
  port: 0

spring:
  aop:
    proxy-target-class: true
  session:
    store-type: jdbc

logging:
  level:
    ROOT: ERROR
    com.example.proxy.Application: INFO
    com.netflix.zuul: DEBUG
    org.springframework.cloud.netflix.zuul: DEBUG
    org.springframework.security.oauth2: DEBUG
